### ISSUE TITLE
请问parser.model和pos.model怎么下载？我用md5值磁力下载不了

### ISSUE THREAD

**Issue by Yewx0310** [Tiffanyccchen/Easy-Event-Extraction#2]

**Comment by tiffanycchen** [comment]
Follow這裡的instruction應該就下載得到了。
https://github.com/HIT-SCIR/pyltp

**Comment by Yewx0310** [comment]
This is an automatic reply, confirming that your e-mail was received. Thank you.--------------------------------------------Best WishesWenxue Ye.

**Comment by Yewx0310** [comment]
> Follow這裡的instruction應該就下載得到了。 https://github.com/HIT-SCIR/pyltp

好的，感谢您的回复，我再试试
